name: workloads-generation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - icecream
  - numpy
  - pandas
  - h5py
  - tqdm
  - requests
  - seaborn
  - jax
  - optax
  - joblib
  # indices
  - faiss-cpu
